"""Temporarily change port_ranges to text

Revision ID: a0ff99d47334
Revises: aebb5f24c6cf
Create Date: 2025-08-22 09:11:38.508811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0ff99d47334'
down_revision = 'aebb5f24c6cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('far_rule_services', 'port_ranges',
               existing_type=postgresql.INT4MULTIRANGE(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('far_rule_services', 'port_ranges',
               existing_type=sa.Text(),
               type_=postgresql.INT4MULTIRANGE(),
               existing_nullable=False)
    # ### end Alembic commands ###
