"""Add FAR rule tables for Phase 2.1

Revision ID: aebb5f24c6cf
Revises: d8dd61c600d4
Create Date: 2025-08-22 08:56:05.270200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aebb5f24c6cf'
down_revision = 'd8dd61c600d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('far_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_hash', sa.LargeBinary(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['far_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_far_rules_id'), 'far_rules', ['id'], unique=False)
    op.create_index(op.f('ix_far_rules_request_id'), 'far_rules', ['request_id'], unique=False)
    op.create_table('far_rule_endpoints',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint_type', sa.Text(), nullable=False),
    sa.Column('network_cidr', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['far_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_far_rule_endpoints_id'), 'far_rule_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_far_rule_endpoints_rule_id'), 'far_rule_endpoints', ['rule_id'], unique=False)
    op.create_table('far_rule_services',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('protocol', sa.Text(), nullable=False),
    sa.Column('port_ranges', postgresql.INT4MULTIRANGE(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['far_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_far_rule_services_id'), 'far_rule_services', ['id'], unique=False)
    op.create_index(op.f('ix_far_rule_services_rule_id'), 'far_rule_services', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_far_rule_services_rule_id'), table_name='far_rule_services')
    op.drop_index(op.f('ix_far_rule_services_id'), table_name='far_rule_services')
    op.drop_table('far_rule_services')
    op.drop_index(op.f('ix_far_rule_endpoints_rule_id'), table_name='far_rule_endpoints')
    op.drop_index(op.f('ix_far_rule_endpoints_id'), table_name='far_rule_endpoints')
    op.drop_table('far_rule_endpoints')
    op.drop_index(op.f('ix_far_rules_request_id'), table_name='far_rules')
    op.drop_index(op.f('ix_far_rules_id'), table_name='far_rules')
    op.drop_table('far_rules')
    # ### end Alembic commands ###
