"""Add asset registry tables

Revision ID: af3a92009573
Revises: 18f079abdbc3
Create Date: 2025-08-23 20:52:40.007177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af3a92009573'
down_revision = '18f079abdbc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_registry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False, comment='Primary asset identifier - must be unique'),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('subnet', sa.String(length=50), nullable=True),
    sa.Column('gateway', postgresql.INET(), nullable=True),
    sa.Column('vlan', sa.String(length=20), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=100), nullable=True),
    sa.Column('db_version', sa.String(length=100), nullable=True),
    sa.Column('vcpu', sa.Integer(), nullable=True),
    sa.Column('memory_gb', sa.Float(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('asset_owner', sa.String(length=100), nullable=True),
    sa.Column('asset_criticality', sa.String(length=20), nullable=True),
    sa.Column('patch_level', sa.String(length=50), nullable=True),
    sa.Column('security_zone', sa.String(length=50), nullable=True),
    sa.Column('compliance_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extended_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible JSON storage for additional asset properties'),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_registry_asset_criticality'), 'asset_registry', ['asset_criticality'], unique=False)
    op.create_index(op.f('ix_asset_registry_business_unit'), 'asset_registry', ['business_unit'], unique=False)
    op.create_index(op.f('ix_asset_registry_environment'), 'asset_registry', ['environment'], unique=False)
    op.create_index(op.f('ix_asset_registry_hostname'), 'asset_registry', ['hostname'], unique=False)
    op.create_index(op.f('ix_asset_registry_id'), 'asset_registry', ['id'], unique=False)
    op.create_index(op.f('ix_asset_registry_ip_address'), 'asset_registry', ['ip_address'], unique=True)
    op.create_index(op.f('ix_asset_registry_is_active'), 'asset_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_asset_registry_os'), 'asset_registry', ['os'], unique=False)
    op.create_index(op.f('ix_asset_registry_security_zone'), 'asset_registry', ['security_zone'], unique=False)
    op.create_index(op.f('ix_asset_registry_segment'), 'asset_registry', ['segment'], unique=False)
    op.create_index(op.f('ix_asset_registry_vlan'), 'asset_registry', ['vlan'], unique=False)
    op.create_table('asset_registry_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('asset_data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete asset data at this version'),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of fields that changed'),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous values of changed fields'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_registry_history_asset_id'), 'asset_registry_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_registry_history_change_type'), 'asset_registry_history', ['change_type'], unique=False)
    op.create_index(op.f('ix_asset_registry_history_id'), 'asset_registry_history', ['id'], unique=False)
    op.create_index(op.f('ix_asset_registry_history_ip_address'), 'asset_registry_history', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asset_registry_history_upload_batch_id'), 'asset_registry_history', ['upload_batch_id'], unique=False)
    op.create_table('asset_upload_batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('upload_filename', sa.String(length=500), nullable=False),
    sa.Column('upload_sha256', sa.String(length=64), nullable=False),
    sa.Column('upload_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('created_assets', sa.Integer(), nullable=False),
    sa.Column('updated_assets', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_upload_batches_batch_id'), 'asset_upload_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_asset_upload_batches_id'), 'asset_upload_batches', ['id'], unique=False)
    op.alter_column('far_rules', 'facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # Prior revisions may not have created these indexes/constraints; use IF EXISTS.
    op.execute(sa.text('DROP INDEX IF EXISTS ix_far_rules_facts'))
    op.alter_column('far_tuple_facts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.execute(sa.text(
        'ALTER TABLE far_tuple_facts DROP CONSTRAINT IF EXISTS '
        'far_tuple_facts_rule_id_source_cidr_destination_cidr_key'
    ))
    # 7bd0bc1fde0e enforces uniqueness via ix_far_tuple_facts_tuple, not the constraint name above.
    op.execute(sa.text('DROP INDEX IF EXISTS ix_far_tuple_facts_tuple'))
    for _ix in (
        'idx_far_tuple_facts_facts',
        'idx_far_tuple_facts_rule_id',
        'idx_tuple_facts_clean',
        'idx_tuple_facts_facts',
        'idx_tuple_facts_rule_id',
        'idx_tuple_facts_self_flow',
        'idx_tuple_facts_violations',
        'ix_far_tuple_facts_facts_gin',
    ):
        op.execute(sa.text(f'DROP INDEX IF EXISTS {_ix}'))
    op.execute(sa.text(
        'CREATE INDEX IF NOT EXISTS ix_far_tuple_facts_destination_cidr '
        'ON far_tuple_facts (destination_cidr)'
    ))
    op.execute(sa.text(
        'CREATE INDEX IF NOT EXISTS ix_far_tuple_facts_id ON far_tuple_facts (id)'
    ))
    op.execute(sa.text(
        'CREATE INDEX IF NOT EXISTS ix_far_tuple_facts_source_cidr '
        'ON far_tuple_facts (source_cidr)'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_far_tuple_facts_source_cidr'), table_name='far_tuple_facts')
    op.drop_index(op.f('ix_far_tuple_facts_id'), table_name='far_tuple_facts')
    op.drop_index(op.f('ix_far_tuple_facts_destination_cidr'), table_name='far_tuple_facts')
    op.create_index('ix_far_tuple_facts_facts_gin', 'far_tuple_facts', ['facts'], unique=False, postgresql_using='gin')
    op.create_index('idx_tuple_facts_violations', 'far_tuple_facts', [sa.text("(facts -> 'violation_type'::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_tuple_facts_self_flow', 'far_tuple_facts', [sa.text("(facts -> 'is_self_flow'::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_tuple_facts_rule_id', 'far_tuple_facts', ['rule_id'], unique=False)
    op.create_index('idx_tuple_facts_facts', 'far_tuple_facts', ['facts'], unique=False, postgresql_using='gin')
    op.create_index('idx_tuple_facts_clean', 'far_tuple_facts', [sa.text("(facts -> 'is_clean'::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_far_tuple_facts_rule_id', 'far_tuple_facts', ['rule_id'], unique=False)
    op.create_index('idx_far_tuple_facts_facts', 'far_tuple_facts', ['facts'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('far_tuple_facts_rule_id_source_cidr_destination_cidr_key', 'far_tuple_facts', ['rule_id', 'source_cidr', 'destination_cidr'])
    op.alter_column('far_tuple_facts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_far_rules_facts', 'far_rules', ['facts'], unique=False, postgresql_using='gin')
    op.alter_column('far_rules', 'facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_asset_upload_batches_id'), table_name='asset_upload_batches')
    op.drop_index(op.f('ix_asset_upload_batches_batch_id'), table_name='asset_upload_batches')
    op.drop_table('asset_upload_batches')
    op.drop_index(op.f('ix_asset_registry_history_upload_batch_id'), table_name='asset_registry_history')
    op.drop_index(op.f('ix_asset_registry_history_ip_address'), table_name='asset_registry_history')
    op.drop_index(op.f('ix_asset_registry_history_id'), table_name='asset_registry_history')
    op.drop_index(op.f('ix_asset_registry_history_change_type'), table_name='asset_registry_history')
    op.drop_index(op.f('ix_asset_registry_history_asset_id'), table_name='asset_registry_history')
    op.drop_table('asset_registry_history')
    op.drop_index(op.f('ix_asset_registry_vlan'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_segment'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_security_zone'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_os'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_is_active'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_ip_address'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_id'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_hostname'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_environment'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_business_unit'), table_name='asset_registry')
    op.drop_index(op.f('ix_asset_registry_asset_criticality'), table_name='asset_registry')
    op.drop_table('asset_registry')
    # ### end Alembic commands ###
