"""Add far_requests table

Revision ID: d8dd61c600d4
Revises: ef99f189263d
Create Date: 2025-08-21 21:23:48.075732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dd61c600d4'
down_revision = 'ef99f189263d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('far_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_far_requests_id'), 'far_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_far_requests_id'), table_name='far_requests')
    op.drop_table('far_requests')
    # ### end Alembic commands ###
