"""
FAR Rules API endpoints
Handles CRUD operations and queries for individual firewall rules
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Dict, Any, Optional
from app.core.database import get_db
from app.models.far_rule import FarRule
from app.models.far_request import FarRequest
from app.services.asset_service import AssetService
from app.services.graph_service import GraphService
from app.services.tuple_generation_service import TupleGenerationService
from app.utils.error_handlers import success_response

router = APIRouter(prefix="/rules", tags=["FAR Rules"])


@router.get("/{rule_id}")
def get_far_rule_details(
    rule_id: int,
    format: Optional[str] = None,
    include: Optional[str] = None,
    db: Session = Depends(get_db)
):
    """
    Get detailed information for a specific FAR rule by ID
    
    Query Parameters:
    - format: Output format ('table' for human-readable, 'json' for API format)
    - include: Additional data to include (comma-separated):
      - 'assets': Include matching asset registry information
      - 'graph': Include D3-compatible graph visualization data
      - 'tuples': Include actual network tuples generated by this rule
      - 'analysis': Include security analysis and recommendations
      - 'all': Include all available data
    
    Returns comprehensive rule details including:
    - Basic rule information (action, direction, etc.)
    - All source and destination endpoints
    - All services (protocols and port ranges)
    - Computed facts (if available)
    - Related request information
    - Optional: Asset details, graph data, security analysis
    """
    # Get the rule with its relationships
    rule = db.query(FarRule).filter(FarRule.id == rule_id).first()
    if not rule:
        raise HTTPException(status_code=404, detail=f"Rule {rule_id} not found")
    
    # Parse include parameter
    includes = []
    if include:
        if include == 'all':
            includes = ['assets', 'graph', 'tuples', 'analysis']
        else:
            includes = [item.strip() for item in include.split(',')]
    
    # Get request information
    request_info = {
        "id": rule.request.id,
        "title": rule.request.title,
        "external_id": rule.request.external_id,
        "status": rule.request.status
    }
    
    # Organize endpoints by type
    sources = []
    destinations = []
    for endpoint in rule.endpoints:
        endpoint_data = {"network_cidr": endpoint.network_cidr}
        if endpoint.endpoint_type == 'source':
            sources.append(endpoint_data)
        elif endpoint.endpoint_type == 'destination':
            destinations.append(endpoint_data)
    
    # Format services
    services = []
    for service in rule.services:
        services.append({
            "protocol": service.protocol,
            "port_ranges": str(service.port_ranges)  # PostgreSQL multirange format
        })
    
    # Parse facts if available
    facts = rule.facts if rule.facts is not None else None
    facts_dict = facts if facts is not None and isinstance(facts, dict) else {}
    
    # Calculate tuple estimate using TupleGenerationService
    tuple_service = TupleGenerationService()
    tuple_estimate = tuple_service.calculate_tuple_estimate(
        len(sources), len(destinations), len(services)
    ) if sources and destinations else 0
    
    # Base response
    response = {
        "rule_id": rule_id,
        "request": request_info,
        "rule_details": {
            "action": rule.action,
            "direction": rule.direction,
            "created_at": rule.created_at.isoformat(),
            "canonical_hash": rule.canonical_hash.hex() if rule.canonical_hash is not None else None
        },
        "endpoints": {
            "sources": sources,
            "destinations": destinations,
            "source_count": len(sources),
            "destination_count": len(destinations)
        },
        "services": services,
        "service_count": len(services),
        "facts": facts,
        "tuple_estimate": tuple_estimate
    }
    
    # Add optional data based on includes
    if 'assets' in includes:
        response['assets'] = _get_rule_assets(rule_id, sources, destinations, db)
    
    if 'graph' in includes:
        response['graph'] = _get_rule_graph_data(rule_id, sources, destinations, services, db)
    
    if 'tuples' in includes:
        response['tuples'] = _get_rule_tuples(sources, destinations, services)
    
    if 'analysis' in includes:
        response['analysis'] = _get_rule_analysis(rule, facts_dict, sources, destinations, services)
    
    # Format response based on format parameter
    if format == 'table':
        return _format_rule_as_table(response)
    
    return success_response(
        data=response,
        message=f"Retrieved detailed information for rule {rule_id}"
    )


@router.get("/{rule_id}/endpoints", response_model=Dict[str, Any])
def get_rule_endpoints(
    rule_id: int,
    endpoint_type: Optional[str] = None,
    db: Session = Depends(get_db)
):
    """
    Get endpoints for a specific rule, optionally filtered by type
    
    Args:
        rule_id: The ID of the rule
        endpoint_type: Optional filter ('source' or 'destination')
    """
    rule = db.query(FarRule).filter(FarRule.id == rule_id).first()
    if not rule:
        raise HTTPException(status_code=404, detail=f"Rule {rule_id} not found")
    
    endpoints = rule.endpoints
    if endpoint_type:
        endpoints = [ep for ep in endpoints if ep.endpoint_type == endpoint_type]
    
    data = {
        "rule_id": rule_id,
        "endpoints": [
            {
                "id": ep.id,
                "type": ep.endpoint_type,
                "network_cidr": ep.network_cidr
            }
            for ep in endpoints
        ],
        "count": len(endpoints)
    }
    
    message = f"Retrieved {len(endpoints)} endpoints for rule {rule_id}"
    if endpoint_type:
        message += f" (filtered by type: {endpoint_type})"
    
    return success_response(
        data=data,
        message=message,
        metadata={"filter": endpoint_type} if endpoint_type else None
    )


@router.get("/{rule_id}/services", response_model=Dict[str, Any])
def get_rule_services(
    rule_id: int,
    db: Session = Depends(get_db)
):
    """
    Get services (protocols and ports) for a specific rule
    """
    rule = db.query(FarRule).filter(FarRule.id == rule_id).first()
    if not rule:
        raise HTTPException(status_code=404, detail=f"Rule {rule_id} not found")
    
    services = []
    for service in rule.services:
        services.append({
            "id": service.id,
            "protocol": service.protocol,
            "port_ranges": str(service.port_ranges),
            "service_type": TupleGenerationService()._classify_service(
                service.protocol, 
                str(service.port_ranges)
            )
        })
    
    data = {
        "rule_id": rule_id,
        "services": services,
        "count": len(services)
    }
    
    return success_response(
        data=data,
        message=f"Retrieved {len(services)} services for rule {rule_id}"
    )


# Helper functions
def _get_rule_assets(rule_id: int, sources: List[Dict], destinations: List[Dict], db: Session) -> Dict[str, Any]:
    """Get asset registry information for rule endpoints"""
    asset_service = AssetService(db)
    
    # Get assets for the rule endpoints
    source_assets = asset_service.get_assets_for_rule_endpoints(sources, [])
    dest_assets = asset_service.get_assets_for_rule_endpoints([], destinations)
    
    asset_matches = {
        "sources": source_assets,
        "destinations": dest_assets,
        "total_matches": len(source_assets) + len(dest_assets)
    }
    
    return asset_matches


def _get_rule_graph_data(rule_id: int, sources: List[Dict], destinations: List[Dict], services: List[Dict], db: Session) -> Dict[str, Any]:
    """Generate D3-compatible graph data for visualization with asset details"""
    asset_service = AssetService(db)
    graph_service = GraphService(asset_service)
    
    # Use the GraphService to create the rule graph
    graph_data = graph_service.create_rule_graph(
        sources=sources,
        destinations=destinations,
        services=services,
        rule_id=rule_id
    )
    
    return graph_data


def _get_rule_tuples(sources: List[Dict], destinations: List[Dict], services: List[Dict]) -> Dict[str, Any]:
    """Generate actual network tuples for this rule"""
    tuple_service = TupleGenerationService()
    
    # Use the TupleGenerationService to generate tuples
    return tuple_service.generate_rule_tuples(sources, destinations, services)


def _get_rule_analysis(rule: Any, facts: Dict, sources: List[Dict], destinations: List[Dict], services: List[Dict]) -> Dict[str, Any]:
    """Provide security analysis and recommendations for the rule"""
    analysis = {
        "security_score": 0,  # 0-100, higher is better
        "risk_level": "low",
        "issues": [],
        "recommendations": [],
        "compliance": {
            "zero_trust": False,
            "principle_of_least_privilege": True
        }
    }
    
    # Analyze based on facts
    if facts:
        # Check for any-any rules
        if facts.get("src_is_any") or facts.get("dst_is_any"):
            analysis["issues"].append({
                "type": "overly_permissive",
                "severity": "high",
                "description": "Rule uses 0.0.0.0/0 (any) for source or destination",
                "impact": "Allows unrestricted network access"
            })
            analysis["risk_level"] = "high"
            analysis["security_score"] -= 30
            analysis["recommendations"].append("Replace 0.0.0.0/0 with specific IP ranges")
        
        # Check for self-flow
        if facts.get("is_self_flow"):
            analysis["issues"].append({
                "type": "self_flow",
                "severity": "medium",
                "description": "Source and destination networks overlap",
                "impact": "May allow unintended lateral movement"
            })
            analysis["security_score"] -= 10
            analysis["recommendations"].append("Review if self-flow is intentional")
        
        # Check for public IP exposure
        if facts.get("src_has_public") or facts.get("dst_has_public"):
            analysis["issues"].append({
                "type": "public_exposure",
                "severity": "medium",
                "description": "Rule involves public IP addresses",
                "impact": "Potential exposure to internet traffic"
            })
            analysis["security_score"] -= 15
            analysis["recommendations"].append("Ensure public IP access is necessary and properly secured")
        
        # Check tuple expansion
        tuple_count = len(sources) * len(destinations) * max(len(services), 1)
        if tuple_count > 100:
            analysis["issues"].append({
                "type": "high_complexity",
                "severity": "low",
                "description": f"Rule generates {tuple_count} network tuples",
                "impact": "May impact firewall performance"
            })
            analysis["security_score"] -= 5
            analysis["recommendations"].append("Consider breaking into more specific rules")
    
    # Set baseline score
    analysis["security_score"] = max(0, 100 + analysis["security_score"])
    
    # Determine risk level based on score
    if analysis["security_score"] >= 80:
        analysis["risk_level"] = "low"
    elif analysis["security_score"] >= 60:
        analysis["risk_level"] = "medium"
    else:
        analysis["risk_level"] = "high"
    
    return analysis


def _format_rule_as_table(response: Dict[str, Any]) -> Dict[str, Any]:
    """Format rule response as human-readable table data"""
    rule_info = response["rule_details"]
    endpoints = response["endpoints"]
    services = response["services"]
    
    # Create a summary table
    table_data = {
        "rule_summary": {
            "Rule ID": response["rule_id"],
            "Action": rule_info["action"],
            "Direction": rule_info["direction"],
            "Request": f"{response['request']['title']} (ID: {response['request']['id']})",
            "Sources": f"{endpoints['source_count']} networks",
            "Destinations": f"{endpoints['destination_count']} networks",
            "Services": f"{response['service_count']} protocols",
            "Tuple Estimate": response["tuple_estimate"]
        },
        "endpoints_table": {
            "sources": [src["network_cidr"] for src in endpoints["sources"]],
            "destinations": [dst["network_cidr"] for dst in endpoints["destinations"]]
        },
        "services_table": [
            {
                "Protocol": svc["protocol"].upper(),
                "Port Range": svc["port_ranges"].strip('{}').strip('[]'),
                "Service Type": TupleGenerationService()._classify_service(svc["protocol"], svc["port_ranges"])
            }
            for svc in services
        ]
    }
    
    # Add optional sections if present
    if "assets" in response:
        table_data["assets_summary"] = {
            "Total Assets Found": response["assets"]["total_matches"],
            "Source Assets": len(response["assets"]["sources"]),
            "Destination Assets": len(response["assets"]["destinations"])
        }
    
    if "analysis" in response:
        analysis = response["analysis"]
        table_data["security_analysis"] = {
            "Security Score": f"{analysis['security_score']}/100",
            "Risk Level": analysis["risk_level"].upper(),
            "Issues Found": len(analysis["issues"]),
            "Recommendations": len(analysis["recommendations"])
        }
    
    # Include original response for completeness
    table_data["raw_data"] = response
    
    return table_data
